# Got this From ChatGPT coz last therai 
email_list = [
    ("Subject: win lottery guaranteed", "spam"),
    ("Subject: click here to get cash", "spam"),
    ("Subject: million dollars waiting for you", "spam"),
    ("Subject: buy now and save", "spam"),
    ("Subject: credit card offer", "spam"),
    ("Subject: important project update", "not spam"),
    ("Subject: meeting scheduled for tomorrow", "not spam"),
    ("Subject: please find the attached report", "not spam"),
    ("Subject: project status", "not spam"),
    ("Subject: update on our discussion", "not spam"),
    ("Subject: cash prize announcement", "spam"),
    ("Subject: limited time offer", "spam"),
    ("Subject: urgent message from the bank", "spam"),
    ("Subject: conference call tomorrow", "not spam"),
    ("Subject: report ready for review", "not spam"),
    ("Subject: claim your prize now", "spam"),
    ("Subject: get rich quick scheme", "spam"),
    ("Subject: important meeting tomorrow", "not spam"),
    ("Subject: special discount today", "spam"),
    ("Subject: your lottery winnings", "spam"),
    ("Subject: update on the project status", "not spam"),
    ("Subject: schedule for the week", "not spam"),
    ("Subject: cash reward notification", "spam"),
    ("Subject: limited time discount", "spam"),
    ("Subject: exclusive offer for you", "spam"),
    ("Subject: urgent action required", "spam"),
    ("Subject: let's discuss tomorrow", "not spam"),
    ("Subject: report attached", "not spam"),
    ("Subject: claim your cash prize", "spam"),
    ("Subject: amazing offer inside", "spam"),
    ("Subject: important meeting reminder", "not spam"),
    ("Subject: discount code inside", "spam"),
    ("Subject: your winning notification", "spam"),
    ("Subject: update on the project", "not spam"),
    ("Subject: tomorrow's agenda", "not spam"),
    ("Subject: cash reward for you", "spam"),
    ("Subject: last chance to win", "spam"),
    ("Subject: urgent message from the CEO", "spam"),
    ("Subject: tomorrow's conference call", "not spam"),
    ("Subject: quarterly report attached", "not spam"),
    ("Subject: claim your prize today", "spam"),
    ("Subject: become a millionaire", "spam"),
    ("Subject: important meeting update", "not spam"),
    ("Subject: exclusive discount offer", "spam"),
    ("Subject: your lottery prize", "spam"),
    ("Subject: project update for review", "not spam"),
    ("Subject: schedule for the month", "not spam"),
    ("Subject: cash prize winner", "spam"),
    ("Subject: limited-time promotion", "spam"),
    ("Subject: special offer inside", "spam"),
    ("Subject: urgent message from the bank", "spam"),
    ("Subject: let's meet tomorrow", "not spam"),
    ("Subject: report for your review", "not spam"),
    ("Subject: claim your cash reward", "spam"),
    ("Subject: unbeatable discount today", "spam"),
    ("Subject: your exclusive offer", "spam"),
    ("Subject: take urgent action", "spam"),
    ("Subject: meeting tomorrow", "not spam"),
    ("Subject: report with attachment", "not spam"),
    ("Subject: claim your cash prize now", "spam"),
    ("Subject: incredible offer inside", "spam"),
    ("Subject: important meeting notice", "not spam"),
    ("Subject: discount code for you", "spam"),
    ("Subject: your winning claim", "spam"),
    ("Subject: project status update", "not spam"),
    ("Subject: tomorrow's meeting", "not spam"),
    ("Subject: cash reward waiting", "spam"),
    ("Subject: don't miss this chance", "spam"),
    ("Subject: CEO's urgent message", "spam"),
    ("Subject: conference call for tomorrow", "not spam"),
    ("Subject: attached quarterly report", "not spam"),
    ("Subject: claim your prize immediately", "spam"),
    ("Subject: become a millionaire today", "spam"),
    ("Subject: important meeting update", "not spam"),
    ("Subject: special discount for you", "spam"),
    ("Subject: your lottery winnings", "spam"),
    ("Subject: project update for your review", "not spam"),
    ("Subject: schedule for the upcoming week", "not spam"),
    ("Subject: cash prize announcement", "spam"),
    ("Subject: limited time discount offer", "spam"),
    ("Subject: exclusive offer just for you", "spam"),
    ("Subject: urgent action required", "spam"),
    ("Subject: let's meet tomorrow", "not spam"),
    ("Subject: attached report for your reference", "not spam"),
    ("Subject: claim your cash prize now", "spam"),
    ("Subject: amazing offer inside", "spam"),
    ("Subject: important meeting reminder", "not spam"),
    ("Subject: discount code inside", "spam"),
    ("Subject: your winning notification", "spam"),
    ("Subject: project status update", "not spam"),
    ("Subject: agenda for tomorrow", "not spam"),
    ("Subject: cash reward for you", "spam"),
    ("Subject: last opportunity to win", "spam"),
    ("Subject: urgent message from the CEO", "spam"),
    ("Subject: conference call tomorrow", "not spam"),
    ("Subject: quarterly report attached", "not spam"),
    ("Subject: claim your prize today", "spam"),
    ("Subject: become a millionaire today", "spam"),
    ("Subject: important meeting update", "not spam"),
    ("Subject: exclusive discount offer", "spam"),
    ("Subject: your lottery prize", "spam"),
    ("Subject: project update for review", "not spam"),
    ("Subject: schedule for the month", "not spam"),
    ("Subject: cash prize winner", "spam"),
    ("Subject: limited-time promotion", "spam"),
    ("Subject: special offer inside", "spam"),
    ("Subject: urgent message from the bank", "spam"),
    ("Subject: let's meet tomorrow", "not spam"),
    ("Subject: report for your review", "not spam"),
    ("Subject: claim your cash reward", "spam"),
    ("Subject: unbeatable discount today", "spam"),
    ("Subject: your exclusive offer", "spam"),
    ("Subject: take urgent action", "spam"),
    ("Subject: meeting tomorrow", "not spam"),
    ("Subject: report with attachment", "not spam"),
    ("Subject: claim your cash prize now", "spam"),
    ("Subject: incredible offer inside", "spam"),
    ("Subject: important meeting notice", "not spam"),
    ("Subject: discount code for you", "spam"),
    ("Subject: your winning claim", "spam"),
    ("Subject: project status update", "not spam"),
    ("Subject: tomorrow's meeting", "not spam"),
    ("Subject: cash reward waiting", "spam"),
    ("Subject: don't miss this chance", "spam"),
    ("Subject: CEO's urgent message", "spam"),
    ("Subject: conference call for tomorrow", "not spam"),
    ("Subject: attached quarterly report", "not spam"),
    ("Subject: claim your prize immediately", "spam"),
    ("Subject: become a millionaire today", "spam"),
    ("Subject: important meeting update", "not spam"),
    ("Subject: special discount for you", "spam"),
    ("Subject: your lottery winnings", "spam"),
    ("Subject: project update for your review", "not spam"),
    ("Subject: schedule for the upcoming week", "not spam"),
]